/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the AgentGuardrailMetricsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentGuardrailMetricsResponse{}

// AgentGuardrailMetricsResponse struct for AgentGuardrailMetricsResponse
type AgentGuardrailMetricsResponse struct {
	TotalEvaluations   int32                 `json:"totalEvaluations"`
	TotalInterventions int32                 `json:"totalInterventions"`
	GlobalPassRate     float32               `json:"globalPassRate"`
	Guardrails         []GuardrailMetricItem `json:"guardrails"`
}

// NewAgentGuardrailMetricsResponse instantiates a new AgentGuardrailMetricsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentGuardrailMetricsResponse(totalEvaluations int32, totalInterventions int32, globalPassRate float32, guardrails []GuardrailMetricItem) *AgentGuardrailMetricsResponse {
	this := AgentGuardrailMetricsResponse{}
	this.TotalEvaluations = totalEvaluations
	this.TotalInterventions = totalInterventions
	this.GlobalPassRate = globalPassRate
	this.Guardrails = guardrails
	return &this
}

// NewAgentGuardrailMetricsResponseWithDefaults instantiates a new AgentGuardrailMetricsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentGuardrailMetricsResponseWithDefaults() *AgentGuardrailMetricsResponse {
	this := AgentGuardrailMetricsResponse{}
	return &this
}

// GetTotalEvaluations returns the TotalEvaluations field value
func (o *AgentGuardrailMetricsResponse) GetTotalEvaluations() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalEvaluations
}

// GetTotalEvaluationsOk returns a tuple with the TotalEvaluations field value
// and a boolean to check if the value has been set.
func (o *AgentGuardrailMetricsResponse) GetTotalEvaluationsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalEvaluations, true
}

// SetTotalEvaluations sets field value
func (o *AgentGuardrailMetricsResponse) SetTotalEvaluations(v int32) {
	o.TotalEvaluations = v
}

// GetTotalInterventions returns the TotalInterventions field value
func (o *AgentGuardrailMetricsResponse) GetTotalInterventions() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalInterventions
}

// GetTotalInterventionsOk returns a tuple with the TotalInterventions field value
// and a boolean to check if the value has been set.
func (o *AgentGuardrailMetricsResponse) GetTotalInterventionsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalInterventions, true
}

// SetTotalInterventions sets field value
func (o *AgentGuardrailMetricsResponse) SetTotalInterventions(v int32) {
	o.TotalInterventions = v
}

// GetGlobalPassRate returns the GlobalPassRate field value
func (o *AgentGuardrailMetricsResponse) GetGlobalPassRate() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.GlobalPassRate
}

// GetGlobalPassRateOk returns a tuple with the GlobalPassRate field value
// and a boolean to check if the value has been set.
func (o *AgentGuardrailMetricsResponse) GetGlobalPassRateOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GlobalPassRate, true
}

// SetGlobalPassRate sets field value
func (o *AgentGuardrailMetricsResponse) SetGlobalPassRate(v float32) {
	o.GlobalPassRate = v
}

// GetGuardrails returns the Guardrails field value
func (o *AgentGuardrailMetricsResponse) GetGuardrails() []GuardrailMetricItem {
	if o == nil {
		var ret []GuardrailMetricItem
		return ret
	}

	return o.Guardrails
}

// GetGuardrailsOk returns a tuple with the Guardrails field value
// and a boolean to check if the value has been set.
func (o *AgentGuardrailMetricsResponse) GetGuardrailsOk() ([]GuardrailMetricItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Guardrails, true
}

// SetGuardrails sets field value
func (o *AgentGuardrailMetricsResponse) SetGuardrails(v []GuardrailMetricItem) {
	o.Guardrails = v
}

func (o AgentGuardrailMetricsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentGuardrailMetricsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["totalEvaluations"] = o.TotalEvaluations
	toSerialize["totalInterventions"] = o.TotalInterventions
	toSerialize["globalPassRate"] = o.GlobalPassRate
	toSerialize["guardrails"] = o.Guardrails
	return toSerialize, nil
}

type NullableAgentGuardrailMetricsResponse struct {
	value *AgentGuardrailMetricsResponse
	isSet bool
}

func (v NullableAgentGuardrailMetricsResponse) Get() *AgentGuardrailMetricsResponse {
	return v.value
}

func (v *NullableAgentGuardrailMetricsResponse) Set(val *AgentGuardrailMetricsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentGuardrailMetricsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentGuardrailMetricsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentGuardrailMetricsResponse(val *AgentGuardrailMetricsResponse) *NullableAgentGuardrailMetricsResponse {
	return &NullableAgentGuardrailMetricsResponse{value: val, isSet: true}
}

func (v NullableAgentGuardrailMetricsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentGuardrailMetricsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
