/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the GuardrailMetricItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GuardrailMetricItem{}

// GuardrailMetricItem struct for GuardrailMetricItem
type GuardrailMetricItem struct {
	Name          string  `json:"name"`
	Version       string  `json:"version"`
	Direction     string  `json:"direction"`
	Evaluations   int32   `json:"evaluations"`
	Interventions int32   `json:"interventions"`
	FailureRate   float32 `json:"failureRate"`
	PassRate      float32 `json:"passRate"`
}

// NewGuardrailMetricItem instantiates a new GuardrailMetricItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGuardrailMetricItem(name string, version string, direction string, evaluations int32, interventions int32, failureRate float32, passRate float32) *GuardrailMetricItem {
	this := GuardrailMetricItem{}
	this.Name = name
	this.Version = version
	this.Direction = direction
	this.Evaluations = evaluations
	this.Interventions = interventions
	this.FailureRate = failureRate
	this.PassRate = passRate
	return &this
}

// NewGuardrailMetricItemWithDefaults instantiates a new GuardrailMetricItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGuardrailMetricItemWithDefaults() *GuardrailMetricItem {
	this := GuardrailMetricItem{}
	return &this
}

// GetName returns the Name field value
func (o *GuardrailMetricItem) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GuardrailMetricItem) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GuardrailMetricItem) SetName(v string) {
	o.Name = v
}

// GetVersion returns the Version field value
func (o *GuardrailMetricItem) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *GuardrailMetricItem) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *GuardrailMetricItem) SetVersion(v string) {
	o.Version = v
}

// GetDirection returns the Direction field value
func (o *GuardrailMetricItem) GetDirection() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Direction
}

// GetDirectionOk returns a tuple with the Direction field value
// and a boolean to check if the value has been set.
func (o *GuardrailMetricItem) GetDirectionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Direction, true
}

// SetDirection sets field value
func (o *GuardrailMetricItem) SetDirection(v string) {
	o.Direction = v
}

// GetEvaluations returns the Evaluations field value
func (o *GuardrailMetricItem) GetEvaluations() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Evaluations
}

// GetEvaluationsOk returns a tuple with the Evaluations field value
// and a boolean to check if the value has been set.
func (o *GuardrailMetricItem) GetEvaluationsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Evaluations, true
}

// SetEvaluations sets field value
func (o *GuardrailMetricItem) SetEvaluations(v int32) {
	o.Evaluations = v
}

// GetInterventions returns the Interventions field value
func (o *GuardrailMetricItem) GetInterventions() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Interventions
}

// GetInterventionsOk returns a tuple with the Interventions field value
// and a boolean to check if the value has been set.
func (o *GuardrailMetricItem) GetInterventionsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Interventions, true
}

// SetInterventions sets field value
func (o *GuardrailMetricItem) SetInterventions(v int32) {
	o.Interventions = v
}

// GetFailureRate returns the FailureRate field value
func (o *GuardrailMetricItem) GetFailureRate() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.FailureRate
}

// GetFailureRateOk returns a tuple with the FailureRate field value
// and a boolean to check if the value has been set.
func (o *GuardrailMetricItem) GetFailureRateOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FailureRate, true
}

// SetFailureRate sets field value
func (o *GuardrailMetricItem) SetFailureRate(v float32) {
	o.FailureRate = v
}

// GetPassRate returns the PassRate field value
func (o *GuardrailMetricItem) GetPassRate() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PassRate
}

// GetPassRateOk returns a tuple with the PassRate field value
// and a boolean to check if the value has been set.
func (o *GuardrailMetricItem) GetPassRateOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PassRate, true
}

// SetPassRate sets field value
func (o *GuardrailMetricItem) SetPassRate(v float32) {
	o.PassRate = v
}

func (o GuardrailMetricItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GuardrailMetricItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["version"] = o.Version
	toSerialize["direction"] = o.Direction
	toSerialize["evaluations"] = o.Evaluations
	toSerialize["interventions"] = o.Interventions
	toSerialize["failureRate"] = o.FailureRate
	toSerialize["passRate"] = o.PassRate
	return toSerialize, nil
}

type NullableGuardrailMetricItem struct {
	value *GuardrailMetricItem
	isSet bool
}

func (v NullableGuardrailMetricItem) Get() *GuardrailMetricItem {
	return v.value
}

func (v *NullableGuardrailMetricItem) Set(val *GuardrailMetricItem) {
	v.value = val
	v.isSet = true
}

func (v NullableGuardrailMetricItem) IsSet() bool {
	return v.isSet
}

func (v *NullableGuardrailMetricItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGuardrailMetricItem(val *GuardrailMetricItem) *NullableGuardrailMetricItem {
	return &NullableGuardrailMetricItem{value: val, isSet: true}
}

func (v NullableGuardrailMetricItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGuardrailMetricItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
